### PR TITLE
Enable flake8 linter in gates

### PR DESCRIPTION
**Pull request by gaugup**
Signed-off-by: gaugup <gaugup@microsoft.com>

### CODE REVIEW

**Comment by amit-sharma** [comment]
Thank you for fixing the flake8 tests @gaugup
I still see some more errors in the flake8 run above, that we'll need to work on.

**Comment by gaugup** [comment]
> Thank you for fixing the flake8 tests @gaugup
> I still see some more errors in the flake8 run above, that we'll need to work on.

I will take a couple of more days to finish the remaining errors. I hope no PRs are merged in this time.

**Comment by gaugup** [comment]
> > Thank you for fixing the flake8 tests @gaugup
> > I still see some more errors in the flake8 run above, that we'll need to work on.
> 
> I will take a couple of more days to finish the remaining errors. I hope no PRs are merged in this time.

@amit-sharma, I created a milestone https://github.com/interpretml/DiCE/milestone/1 so that we can reduce the cyclometric complexity (https://www.geeksforgeeks.org/cyclomatic-complexity/) of certain methods within DiCE library. This can be done by refactoring certain code in these methods and the work for this milestone is outside the scope of this PR. For now I will set --max-complexity as 30 to avoid the cyclometric complexity to fail the flake8 gate.

**Review by amit-sharma — APPROVED** [review]
thank you @gaugup for this massive effort! Will enable flake8 going forward for every PR.

**Pull request merged**
