### PR TITLE
Make ExplainerBase Abstract Class

### PR DESCRIPTION
**Pull request by gaugup**
The ExplainerBase class doesn't implement _generate_counterfactuals() but expects derived classes to implement this function. Hence, making ExplainerBase class an abstract class and making the method _generate_counterfactuals() an abstract method so that the deriving class always implements it.

Signed-off-by: gaugup <gaugup@microsoft.com>

### CODE REVIEW

**Comment by amit-sharma** [comment]
Thanks @gaugup . I see an error in dice.py. Perhaps class `Dice` needs to inherit from `ExplainerBase` too?

**Comment by gaugup** [comment]
> Thanks @gaugup . I see an error in dice.py. Perhaps class `Dice` needs to inherit from `ExplainerBase` too?

That is weird. I didn't see the error running the unit tests locally. Let me try to reproduce it locally.

**Comment by gaugup** [comment]
> > Thanks @gaugup . I see an error in dice.py. Perhaps class `Dice` needs to inherit from `ExplainerBase` too?
> 
> That is weird. I didn't see the error running the unit tests locally. Let me try to reproduce it locally.

Thanks @amit-sharma  for the suggestion of inheriting from ExplainerBase in dice.py. That helped resolve the error. 

Also, are there any other methods that ExplainerBase expects the sub-classes to implement? Might be good to declare those as abstract in the ExplainerBase class.

**Comment by amit-sharma** [comment]
> > > Thanks @gaugup . I see an error in dice.py. Perhaps class `Dice` needs to inherit from `ExplainerBase` too?
> > 
> > 
> > That is weird. I didn't see the error running the unit tests locally. Let me try to reproduce it locally.
> 
> Thanks @amit-sharma for the suggestion of inheriting from ExplainerBase in dice.py. That helped resolve the error.
> 
> Also, are there any other methods that ExplainerBase expects the sub-classes to implement? Might be good to declare those as abstract in the ExplainerBase class.

no, `_generate_counterfactuals` is the only method. Merging.

**Review by amit-sharma — APPROVED** [review]

**Pull request merged**
